trigger:
- main

jobs:
- job: TerraformInfra
  displayName: "Provision Infrastructure with Terraform"
  timeoutInMinutes: 180

  pool:
    name: Default

  steps:
  - checkout: self

  - script: |
      whoami
      pwd
      ls -la
      which terraform
      terraform --version
    displayName: "Check Agent and Terraform"

  - script: |
      cat > terraform.tfvars <<EOF
      resource_group_name   = "rg-epicbook-capstone"
      location              = "UK South"
      vnet_name             = "vnet-epicbook"
      frontend_subnet_name  = "frontend-subnet"
      backend_subnet_name   = "backend-subnet"
      frontend_vm_name      = "epicbook-frontend-vm"
      backend_vm_name       = "epicbook-backend-vm"
      admin_username        = "azureuser"
      ssh_public_key_path   = "/home/sonny_h0b2ruu/.ssh/epicbook_azure_key.pub"
      mysql_server_name     = "epicbookmysql123456"
      mysql_admin_username  = "epicadmin"
      mysql_admin_password  = "UseAStrongPassword123!"
      mysql_database_name   = "bookstore"
      EOF

      echo "terraform.tfvars created"
      cat terraform.tfvars
    displayName: "Create terraform.tfvars"

  - task: AzureCLI@2
    displayName: "Terraform Init"
    inputs:
      azureSubscription: 'epicbook-azure-rm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)
        export TF_INPUT=0
        terraform init

  - task: AzureCLI@2
    displayName: "Terraform Validate"
    inputs:
      azureSubscription: 'epicbook-azure-rm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)
        export TF_INPUT=0
        terraform validate

  - task: AzureCLI@2
    displayName: "Terraform Plan"
    inputs:
      azureSubscription: 'epicbook-azure-rm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)
        export TF_INPUT=0
        terraform plan -input=false -out=tfplan

  - task: AzureCLI@2
    displayName: "Terraform Apply"
    inputs:
      azureSubscription: 'epicbook-azure-rm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)
        export TF_INPUT=0
        terraform apply -input=false -auto-approve tfplan

  - task: AzureCLI@2
    displayName: "Terraform Outputs"
    inputs:
      azureSubscription: 'epicbook-azure-rm'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)
        terraform output